config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#index'
  get "home/about" => "homes#about"
  resources :books
  resources :users
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
  belongs_to :user
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, uniqueness: true, presence: true, length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}

  has_many :books, dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?

	     def after_sign_up_path_for(resource)
		 	user_path(current_user)
	     end
		 def after_sign_in_path_for(resource)
		 	user_path(current_user)
		 end
		protected

		def configure_permitted_parameters
			devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name])
			devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
		end
	

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @user = current_user
    @books = Book.all
    @book = Book.new
  end
    
  def create
    @user = current_user
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice:'You have creatad book successfully.'
    else
      render :index
    end
  end
  
  
  def show
    @book = Book.new
    @books = Book.all
    @new_book = Book.find(params[:id])
    @user = User.find(@new_book.user.id)
  end
  
  def edit
    @book = Book.find(params[:id])
    if current_user.id != @book.user.id
      redirect_to books_path
    end
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice:'You have updated book successfully.'
    else
      render :edit
    end
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = current_user
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = Book.all
  end
  
  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice:'You have updated user successfully.'
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_new.html.erb
<h2>New book</h2>
 <%= form_with model:@book, local:true do |f| %>
  <div class="form-group">
    <%= f.label :title, "Title" %>
    <%= f.text_field :title, class:'col-md-12' %>
  </div>
  <div class="form-group">
    <%= f.label :body, "Opinion" %>
    <%= f.text_area :body, class:'col-md-12' %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book', class:"btn btn-success" %>
  </div>
<% end %>

app/views/books/edit.html.erb
 <div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
 <h1>Editing Book</h2>
 <% if @book.errors.any? %>
      <div id="error_explanation">
        <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
        <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
      <% end %>
   <%= form_with model:@book, local:true do |f| %>
        <div class="form-group">
          <%= f.label :title, 'Title' %>
          <%= f.text_field :title, class:'col-xs-12' %>
        </div>
        <div class="form-group">
          <%= f.label :body, 'Opinion' %>
          <%= f.text_area :body,class:'col-xs-12'  %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update Book', class:'btn btn-primary col-xs-12' %>
        </div>
      <% end %>
      <%= link_to 'Show', book_path(@book.id) %>
      <span>|</span>
      <%= link_to 'Back', books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">
    <% if @book.errors.any? %>
     <div id="error_explanation">
      <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
     </div>
    <% end %>
    <div class="col-md-3">
      <%= render 'users/info', user: @user %>
      <%= render 'books/new', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
       <h2>Books</h2>
        <table class="table table-hover table-inverse">
         <thread>
          <tr>
           <th></th>
           <th>Title</th>
           <th>Opinion</th>
          </tr>
         </thread>
         <tbody>
         <% @books.each do |book| %>
          <tr>
           <td><%= link_to (attachment_image_tag book.user, :profile_image_id, size:"40x40", format:'jpeg', fallback:"no_image.jpg"), user_path(book.user.id) %></td>
           <td><%= link_to book.title, book_path(book.id) %></td>
           <td><%= book.body %></td>
          </tr>
         <% end %>
         </tbody>
        </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container" >
  <div class="row">
    <div class="col-md-3">
     <%= render 'users/info', user: @user %>
     <%= render 'books/new', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
     <h2>Book detail</h2>
      <table class="table">
       <tr>
        <td>
         <%= link_to user_path(@new_book.user.id) do %>
         <%= attachment_image_tag @new_book.user, :profile_image_id, size:"40x40", format:'jpeg', fallback:"no_image.jpg" %>
         <%= @new_book.user.name %>
         <% end %>
        </td>
        <td><%= @new_book.title %></td>
        <td><%= @new_book.body %></td>
        <% if @new_book.user.id == current_user.id %>
        <td><%= link_to 'Edit', edit_book_path(@new_book.id), class:'btn btn-success btn-sm' %></td>
        <td><%= link_to 'Destroy', book_path, method: :delete, class:'btn btn-danger btn-sm'  %></td>
        <% end %>
       </tr>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/index.html.erb
<main>
 <div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
         <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
         <%= link_to "Sign up", new_user_registration_path, class:"btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/ce9a8ab6cf.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
           <li><%= link_to "Home", user_path(current_user.id), class:'fas fa-home nav-link text-light' %></li>

           <li><%= link_to "Users", users_path, class:'fas fa-users nav-link text-light' %></li>

           <li><%= link_to "Books", books_path,class:'fas fa-book-open nav-link text-light'  %></li>

           <li><%= link_to "logout",destroy_user_session_path, class:'fas fa-sign-out-alt nav-link text-light', method: :delete %>

           <% else %>
           <li><%= link_to 'Home', root_path, class:'fas fa-link nav-link text-light' %></li>

           <li><%= link_to 'About', home_about_path,  class:'fas fa-home nav-link text-light' %></li>

           <li><%= link_to 'sign up', new_user_registration_path,  class:'fas fa-user-plus nav-link text-light' %></li>

           <li><%= link_to 'login', new_user_session_path,  class:'fas fa-sign-in-alt nav-link text-light' %></li>
           <% end %>
        </ul>
      </div>
    </div>
    </nav>
    <% if flash[:notice] %>
      <p class="text-success"><%= flash[:notice] %></p>
    <% end %>
    <%= yield %>
    <footer>
     <div class="container mt-5">
    	<div class="row">
    	 <div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
       </div>
      </div>
     </div>
    </footer>
  </body>
</html>

app/views/users/_info.html.erb
<h2>User info</h2>
<%= attachment_image_tag user, :profile_image, size:"100x100", format:'jpeg', fallback:"no_image.jpg" %>
 <table class="table">
   <tbody>
     <tr>
       <th>name</th>
       <td><%= user.name %></td>
     </tr>
     <tr>
       <th>introduction</th>
       <td><%= user.introduction %></td>
     </tr>
   </tbody>
 </table>
 <%= link_to edit_user_path(user) do %>
   <div class= "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_5190"></div>

   <% end %>

app/views/users/edit.html.erb
<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   <h2>User info</h2>
   <%= form_with model:@user, local: true do |f| %>
    <div id="error_explanation">
      <h3><%= @user.errors.count %> error prohibited this obj from being saved:</h3>
       <ul>
          <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
          <% end %>
       </ul>
    </div>

     <div class="form-group">
      <label for="user_name">Name</label>
      <%= f.text_field :name, class:'' %>
     </div>

     <div class="form-group">
      <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback:"no_image.jpg" %>
      <label for="user_image">Image</label>
      <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
     </div>

     <div class="form-group">
      <label for="user_introduction">Introdction</h3>
      <%= f.text_area :introduction, class:'' %>
     </div>
      <%= f.submit 'Update User' %>
   <% end %>
  </div>
 </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
     <%= render 'users/info', user: @user %>
     <%= render 'books/new', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
     <h2>Users</h2>
      <table class="table">
       <thead>
        <tr>
         <th>image</th>
         <th>name</th>
         <th></th>
        </tr>
       </thead>
       <tbody>
       <% @users.each do |user| %>
       <tr>
        <td><%= attachment_image_tag user, :profile_image, size:"50x50", format:'jpeg', fallback:"no_image.jpg" %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user.id) %></td>
       </tr>
       <% end %>
       </tbody>
      </table>
    </div>
  </diV>
 </div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/info', user: @user %>
      <%= render 'books/new', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <% if book.user.id == @user.id %>
              <tr>
                <td><%= link_to (attachment_image_tag book.user, :profile_image_id, size:"40x40", format:'jpeg', fallback:"no_image.jpg"), user_path(book.user.id) %></td>
                <td><%= link_to book.title, book_path(book.id) %></td>
                <td><%= book.body %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>